[tool.ruff]
lint.select = [
    "BLE",
    "F401", "F821", "F823", "F841",
    "PL", "PLR0913","PLR0914", "PLR0916",
    "YTT",
    "F541",
    "PIE",
    "B006",
    "PLW", # mainly for PLW0211
]

lint.ignore = ["E501", "PLR2004"]

lint.preview = true
lint.explicit-preview-rules = true
exclude = ["argus/"]

target-version = "py310"

force-exclude = true
line-length = 240
respect-gitignore = true

[tool.ruff.lint.pylint]
max-args = 12
max-statements = 100
max-branches = 24
max-locals = 15
