name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
        cache: 'pip'
    - name: Install the project
      run: uv pip install -r requirements.txt --system
    - name: Run pre-commit
      run: pre-commit run --all-files
